service:
  name: spiders-node
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
       
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  lions:
    handler: src/teams/lions.test
    events:
      - http:
          method: get
          path: test
  tigers:
    handler: src/teams/tigers.players
    events:
      - http:
          method: get
          path: players