service:
  name: spiders-node
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  bye:
    handler: src/bye.bye
    events:
      - http:
          method: get
          path: hello 
  match:
    handler: src/match.match
    events:
      - http:
          method: get
          path: hello         
